Drop deprecated SubstrateAnalyzer + ZSLGenerator reexports (#2981)
* breaking: remove deprecated re-export of SubstrateAnalyzer, ZSLGenerator from pymatgen/analysis/substrate_analyzer.py

now available from pymatgen.analysis.interfaces

* drop custom ArrayLike fallback type, make numpy import required

* breaking: drop deprecated kwarg include_unprocessed_entries from PourbaixDiagram.as_dict()

* drop deprecated get_void_volume_surfarea() and test from pymatgen/io/zeopp.py

fix mypy ignore

* drop deprecated frequencies @property from class Outcar

* fix mypy

* fix pymatgen/analysis/tests/test_pourbaix_diagram.py:262: AssertionError

assert {e.name for e in new.stable_entries} == {
            "ZnO(s)",
            "Zn[2+]",
            "ZnHO2[-]",
            "ZnO2[2-]",
            "Zn(s)",
            "ZnO2(s)",
            "ZnH(s)",
        }, "List of stable entries for unfiltered pbx does not match"
E       AssertionError: List of stable entries for unfiltered pbx does not match
E       assert {'Zn(s)', 'Zn...-]', 'Zn[2+]'} == {'Zn(s)', 'Zn...nO2[2-]', ...}
E         Extra items in the right set:
E         'ZnH(s)'
E         'ZnO2(s)'
E         Use -v to get more diff